import { jsPDF } from 'jspdf';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useState } from 'react';

interface ChatMessageProps {
    role: 'user' | 'assistant';
    content: string;
    timestamp?: string;
    canFix?: boolean;
    onApplyFix?: () => void;
    downloadUrl?: string;
    agentType?: string;
}

interface ExportLink {
    url: string;
    filename: string;
    type: 'pdf' | 'json';
}

const ChatMessage = ({ role, content, timestamp, canFix, onApplyFix, downloadUrl, agentType }: ChatMessageProps) => {
    const isAssistant = role === 'assistant';
    const [exportLinks, setExportLinks] = useState<ExportLink[]>([]);
    const [isExportingPDF, setIsExportingPDF] = useState(false);
    const [isExportingJSON, setIsExportingJSON] = useState(false);

    const handleExportJSON = () => {
        setIsExportingJSON(true);
        try {
            const data = {
                role,
                content,
                timestamp: timestamp || new Date().toISOString(),
                status: 'success',
                agent: 'Orchestrator'
            };
            const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
            const url = URL.createObjectURL(blob);
            const filename = `sdlc-response-${new Date().getTime()}.json`;

            // Add to export links for user to download
            setExportLinks(prev => [...prev, { url, filename, type: 'json' }]);
        } finally {
            setIsExportingJSON(false);
        }
    };

    const handleExportPDF = () => {
        setIsExportingPDF(true);
        try {
            const doc = new jsPDF();
            const pageWidth = doc.internal.pageSize.getWidth();
            const pageHeight = doc.internal.pageSize.getHeight();
            const margin = 20;
            const width = pageWidth - (margin * 2);
            let cursorY = 25;

            // Cover Page Logic
            const createCoverPage = () => {
                // Background branding
                doc.setFillColor(15, 23, 42); // Very dark slate
                doc.rect(0, 0, pageWidth, pageHeight, 'F');

                // Decorative lines
                doc.setDrawColor(30, 41, 59);
                doc.setLineWidth(0.5);
                for (let i = 0; i < pageWidth; i += 10) {
                    doc.line(i, 0, i, pageHeight);
                }

                // Title Box
                doc.setFillColor(30, 41, 59);
                doc.rect(20, pageHeight / 2 - 40, pageWidth - 40, 80, 'F');
                doc.setDrawColor(51, 65, 85);
                doc.rect(20, pageHeight / 2 - 40, pageWidth - 40, 80, 'D');

                // Text
                doc.setTextColor(255, 255, 255);
                doc.setFont('helvetica', 'bold');
                doc.setFontSize(28);
                const titleLines = doc.splitTextToSize("ARCHITECTURAL BLUEPRINT & SDLC SPECIFICATION", width - 20);
                doc.text(titleLines, margin + 10, pageHeight / 2 - 15);

                doc.setFontSize(10);
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(148, 163, 184);
                doc.text("GENERATED BY COASTALSEVEL ORCHESTRATOR v2.0", margin + 10, pageHeight / 2 + 25);

                // Footer Info
                doc.setFontSize(9);
                doc.text(`SESSION ID: ${Math.random().toString(36).substring(7).toUpperCase()}`, margin + 10, pageHeight - 30);
                doc.text(`DATE: ${new Date().toLocaleDateString()}`, margin + 10, pageHeight - 25);
                doc.text("CONFIDENTIAL | FOR AUTHORIZED PERSONNEL ONLY", margin + 10, pageHeight - 20);

                doc.addPage();
            };

            const addHeader = (pageNum: number) => {
                doc.setFillColor(248, 250, 252);
                doc.rect(0, 0, pageWidth, 22, 'F');
                doc.setFont('helvetica', 'bold');
                doc.setFontSize(8);
                doc.setTextColor(71, 85, 105);
                doc.text("COASTALSEVEL SDLC ORCHESTRATOR - TECHNICAL BLUEPRINT", margin, 14);
                doc.setFont('helvetica', 'normal');
                doc.text(`PAGE ${pageNum}`, pageWidth - margin - 12, 14);
                doc.setDrawColor(226, 232, 240);
                doc.line(0, 22, pageWidth, 22);
            };

            const addFooter = () => {
                doc.setFont('helvetica', 'normal');
                doc.setFontSize(7);
                doc.setTextColor(148, 163, 184);
                doc.text(`© ${new Date().getFullYear()} coastalsevel Systems. Technical Intelligence Division.`, margin, pageHeight - 12);
                doc.text(`Doc Ref: AG-${Date.now().toString().slice(-6)}`, pageWidth - margin - 30, pageHeight - 12);
            };

            // Execution
            createCoverPage();
            let pageNum = 1;
            addHeader(pageNum);

            doc.setFillColor(30, 41, 59);
            doc.rect(margin, cursorY, width, 18, 'F');
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(14);
            doc.setTextColor(255, 255, 255);
            doc.text("EXECUTIVE ARCHITECTURAL SUMMARY", margin + 5, cursorY + 11);
            cursorY += 28;

            const lines = content.split('\n');
            lines.forEach((line) => {
                const isDiagram = line.startsWith(' ') || line.startsWith('|') || line.startsWith('+') || line.startsWith('-') || line.startsWith('[');
                const isHeader = line.startsWith('#');

                if (isDiagram) {
                    doc.setFillColor(249, 250, 251);
                    doc.setDrawColor(243, 244, 246);
                    const wrappedDiagram = doc.splitTextToSize(line, width - 10);
                    const blockHeight = wrappedDiagram.length * 4.5 + 4;

                    if (cursorY + blockHeight > pageHeight - 25) {
                        addFooter();
                        doc.addPage();
                        pageNum++;
                        addHeader(pageNum);
                        cursorY = 30;
                    }
                    doc.rect(margin, cursorY - 3, width, blockHeight, 'F');
                    doc.setFont('courier', 'normal');
                    doc.setFontSize(8.5);
                    doc.setTextColor(31, 41, 55);
                    wrappedDiagram.forEach((subline: string) => {
                        doc.text(subline, margin + 5, cursorY);
                        cursorY += 4.5;
                    });
                    cursorY += 4;
                } else if (isHeader) {
                    doc.setFont('helvetica', 'bold');
                    const level = line.match(/^#+/)?.[0].length || 1;
                    const fontSize = level === 1 ? 16 : 12;
                    doc.setFontSize(fontSize);
                    doc.setTextColor(15, 23, 42);

                    if (cursorY > pageHeight - 30) {
                        addFooter();
                        doc.addPage();
                        pageNum++;
                        addHeader(pageNum);
                        cursorY = 30;
                    }

                    doc.text(line.replace(/^#+\s*/, ''), margin, cursorY);
                    cursorY += fontSize / 1.5 + 4;
                } else {
                    doc.setFont('helvetica', 'normal');
                    doc.setFontSize(10);
                    doc.setTextColor(51, 65, 85); // Slate 700

                    const wrappedText = doc.splitTextToSize(line, width);
                    wrappedText.forEach((subline: string) => {
                        if (cursorY > pageHeight - 25) {
                            addFooter();
                            doc.addPage();
                            pageNum++;
                            addHeader(pageNum);
                            cursorY = 30;
                        }
                        doc.text(subline, margin, cursorY);
                        cursorY += 5.5;
                    });
                }
            });

            addFooter();


            // Generate blob and create persistent download link
            const pdfBlob = doc.output('blob');
            const url = URL.createObjectURL(pdfBlob);
            const filename = `Architectural_Blueprint_${new Date().getTime()}.pdf`;

            // Add to export links for user to download
            setExportLinks(prev => [...prev, { url, filename, type: 'pdf' }]);
        } finally {
            setIsExportingPDF(false);
        }
    };

    return (
        <div className={`flex w-full mb-8 ${isAssistant ? 'justify-start' : 'justify-end'} animate-in fade-in slide-in-from-bottom-4 duration-500`}>
            <div className={`flex max-w-[85%] md:max-w-[75%] gap-4 ${isAssistant ? 'flex-row' : 'flex-row-reverse'}`}>
                {/* Avatar */}
                <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center text-sm shadow-xl ${isAssistant
                    ? 'bg-accent text-white ring-2 ring-accent/20'
                    : 'bg-zinc-800 text-zinc-300 ring-2 ring-zinc-700/50'
                    }`}>
                    {isAssistant ? (
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
                        </svg>
                    ) : (
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                        </svg>
                    )}
                </div>

                {/* Content Bubble */}
                <div className="flex flex-col gap-2">
                    <div className={`px-5 py-3 rounded-2xl text-[15px] leading-relaxed shadow-sm ${isAssistant
                        ? 'bg-zinc-900/40 border border-zinc-800/50 text-zinc-200'
                        : 'bg-accent text-white border border-accent/20'
                        }`}>
                        <div className="prose prose-invert prose-sm max-w-none prose-p:leading-relaxed prose-pre:bg-black/50 prose-pre:border prose-pre:border-white/10 prose-code:text-accent prose-a:text-blue-400 prose-a:no-underline hover:prose-a:underline">
                            <ReactMarkdown
                                remarkPlugins={[remarkGfm]}
                                components={{
                                    a: ({ node, href, children, ...props }) => {
                                        // Convert relative API URLs to full backend URLs
                                        const fullHref = href?.startsWith('/api/')
                                            ? `http://localhost:8001${href}`
                                            : href;

                                        // Check if it's a download link
                                        const isDownloadLink = href?.includes('/download/');

                                        return (
                                            <a
                                                href={fullHref}
                                                {...(isDownloadLink && { download: true })}
                                                target={isDownloadLink ? '_self' : '_blank'}
                                                rel="noopener noreferrer"
                                                className="text-blue-400 hover:text-blue-300 underline decoration-dotted font-medium"
                                                {...props}
                                            >
                                                {children}
                                            </a>
                                        );
                                    }
                                }}
                            >
                                {content}
                            </ReactMarkdown>
                        </div>
                    </div>

                    {/* Action Buttons for Assistant */}
                    {isAssistant && (
                        <>
                            <div className="flex items-center gap-3 px-1">
                                <button
                                    onClick={handleExportPDF}
                                    disabled={isExportingPDF}
                                    className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-zinc-500 hover:text-white transition-colors group disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    {isExportingPDF ? (
                                        <svg className="w-3.5 h-3.5 animate-spin" fill="none" viewBox="0 0 24 24">
                                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                        </svg>
                                    ) : (
                                        <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                        </svg>
                                    )}
                                    {isExportingPDF ? 'Generating...' : 'Export PDF'}
                                </button>
                                <span className="w-1 h-1 rounded-full bg-zinc-800" />
                                <button
                                    onClick={handleExportJSON}
                                    disabled={isExportingJSON}
                                    className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-zinc-500 hover:text-white transition-colors group disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    {isExportingJSON ? (
                                        <svg className="w-3.5 h-3.5 animate-spin" fill="none" viewBox="0 0 24 24">
                                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                        </svg>
                                    ) : (
                                        <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                                        </svg>
                                    )}
                                    {isExportingJSON ? 'Generating...' : 'Export JSON'}
                                </button>

                                {canFix && onApplyFix && (
                                    <>
                                        <span className="w-1 h-1 rounded-full bg-zinc-800" />
                                        <button
                                            onClick={onApplyFix}
                                            className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-emerald-500 hover:text-emerald-400 transition-colors group"
                                        >
                                            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
                                            </svg>
                                            Fix Issues
                                        </button>
                                    </>
                                )}

                                {downloadUrl && (
                                    <>
                                        <span className="w-1 h-1 rounded-full bg-zinc-800" />
                                        <a
                                            href={`http://localhost:8001${downloadUrl}`}
                                            download
                                            className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-blue-500 hover:text-blue-400 transition-colors group"
                                        >
                                            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a2 2 0 002 2h12a2 2 0 002-2v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                                            </svg>
                                            Download {agentType?.replace(/_/g, ' ').toUpperCase() || 'REPORT'}
                                        </a>
                                    </>
                                )}
                            </div>

                            {/* Export Download Links */}
                            {exportLinks.length > 0 && (
                                <div className="flex flex-col gap-2 px-1 mt-2">
                                    {exportLinks.map((link, index) => (
                                        <a
                                            key={index}
                                            href={link.url}
                                            download={link.filename}
                                            className="flex items-center gap-2 text-xs text-blue-400 hover:text-blue-300 transition-colors animate-in fade-in slide-in-from-left-2 duration-300 underline decoration-dotted"
                                        >
                                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                            </svg>
                                            <span className="font-medium">Download {link.type.toUpperCase()}: {link.filename}</span>
                                        </a>
                                    ))}
                                </div>
                            )}
                        </>
                    )}
                </div>
            </div>
        </div>
    );
};

export default ChatMessage;
