import os
import tempfile
import uuid
from datetime import datetime
from typing import Dict, Optional
import logging

from app.services.llm import llm_service
from app.core.storage import register_report

logger = logging.getLogger(__name__)

class ImpactAnalysisService:
    def __init__(self):
        self.name = "Impact Analysis Agent"

    async def analyze_impact(self, prd_content: str, architecture_content: str, github_url: Optional[str] = None) -> Dict[str, str]:
        """
        Analyze technical and business impact based on PRD and architecture.
        
        Args:
            prd_content: content of the PRD
            architecture_content: content of the architecture doc
            github_url: optional github url
            
        Returns:
            Dict containing report_content and file_id
        """
        try:
            logger.info(f"[Impact Analysis Agent] Starting impact analysis...")
            
            # Create comprehensive system prompt for impact analysis
            system_prompt = """You are a Senior Business & Technical Impact Analyst with expertise in:
- Business Impact Assessment (ROI, Cost-Benefit Analysis)
- Technical Risk Assessment (Scalability, Security, Performance)
- Resource Planning & Timeline Estimation
- Stakeholder Impact Analysis

Your task is to provide a comprehensive impact analysis report that covers:

1. BUSINESS IMPACT ANALYSIS
   - Market opportunity assessment
   - Revenue potential and ROI projections
   - Cost analysis (development, maintenance, operational)
   - Competitive advantage assessment
   - User adoption predictions

2. TECHNICAL IMPACT ANALYSIS
   - Technical complexity assessment
   - Scalability requirements and challenges
   - Security implications and risks
   - Performance considerations
   - Integration complexity
   - Technology stack evaluation

3. RISK ASSESSMENT
   - Technical risks and mitigation strategies
   - Business risks and contingency plans
   - Timeline risks and buffer recommendations
   - Resource risks and alternatives

4. RESOURCE PLANNING
   - Development team requirements
   - Timeline estimation with milestones
   - Budget allocation recommendations
   - Infrastructure requirements

5. STAKEHOLDER IMPACT
   - End-user impact and change management
   - Internal team impact
   - External partner/vendor impact
   - Compliance and regulatory considerations

Provide specific, actionable insights with quantitative estimates where possible.
Format your response as a professional report with clear sections and bullet points."""

            # Create user prompt with available context
            user_prompt = f"""
PROJECT REQUIREMENTS DOCUMENT:
{prd_content[:2000]}

SYSTEM ARCHITECTURE:
{architecture_content[:2000]}

GITHUB REPOSITORY: {github_url or 'Not provided'}

Please provide a comprehensive impact analysis covering all business and technical aspects of this project.
"""

            # Get LLM response
            impact_report = await llm_service.get_response(user_prompt, system_prompt)
            
            # Ensure the report has a professional header
            if not impact_report.startswith("#"):
                impact_report = f"# COMPREHENSIVE IMPACT ANALYSIS REPORT\n\n{impact_report}"
            
            # Generate PDF report (simplified - create text file for now)
            file_id = str(uuid.uuid4())
            temp_dir = tempfile.gettempdir()
            report_path = os.path.join(temp_dir, f"impact_analysis_{file_id}.txt")
            
            # Create detailed report content
            full_report = f"""IMPACT ANALYSIS REPORT
Generated: {datetime.utcnow().isoformat()}
Project: {github_url or 'Unknown Project'}

{impact_report}

---
Report ID: {file_id}
Generated by: Impact Analysis Agent
"""
            
            # Write report to file
            with open(report_path, "w", encoding="utf-8") as f:
                f.write(full_report)
            
            # Register the report for download
            register_report(file_id, report_path)
            
            logger.info(f"[Impact Analysis Agent] Impact analysis completed successfully")
            
            return {
                "report_content": impact_report,
                "file_id": file_id
            }
            
        except Exception as e:
            logger.error(f"Impact Analysis Agent error: {e}")
            return {
                "report_content": f"Error: Impact analysis failed - {str(e)}",
                "file_id": None
            }

# Create service instance
impact_analysis_service = ImpactAnalysisService()