import asyncio
import os
import sys
import shutil
import tempfile
from unittest.mock import MagicMock, patch

# Add the project root to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')))

from app.agents.code_review.app.services.fix_service import fix_repo_code
from app.agents.code_review.app.services.pdf_service import code_review_pdf_service

async def mock_fix_code_with_llm(original_code, issue_description, file_path):
    return original_code + "\n# Fixed by AI\ndef fixed_function(): pass\n"

async def test_professional_workflow():
    print("🚀 Starting Code Review Professional Workflow Verification...")
    
    # Create a temp repo
    with tempfile.TemporaryDirectory() as tmp_dir:
        repo_path = os.path.join(tmp_dir, "repo")
        os.makedirs(repo_path)
        
        test_file = os.path.join(repo_path, "main.py")
        with open(test_file, "w") as f:
            f.write("def start():\n    print('Hello World')\n")
        
        issues = {
            "main.py": ["Insecure print statement", "Missing docstring"]
        }
        
        # Test 1: Async FixService
        print("🧪 Testing Async FixService...")
        with patch('app.agents.code_review.app.services.fix_service.fix_code_with_llm', side_effect=mock_fix_code_with_llm):
            changes = await fix_repo_code(repo_path, issues)
            
        if not changes or len(changes) == 0:
            print("❌ Error: No changes generated by FixService")
            return
            
        print(f"✅ FixService generated {len(changes)} changes")
        print(f"✅ Changes Summary: {changes[0]['fix_explanation']}")
        
        # Test 2: PDF Generation
        print("🧪 Testing CodeReviewPDFService...")
        file_id = "test-uuid-123"
        pdf_path = code_review_pdf_service.generate_report(
            "https://github.com/user/repo",
            "https://github.com/user/repo-fixed",
            changes,
            file_id
        )
        
        if os.path.exists(pdf_path):
            print(f"✅ PDF Report generated at: {pdf_path}")
            print(f"✅ PDF Size: {os.path.getsize(pdf_path)} bytes")
        else:
            print("❌ Error: PDF Report was not generated")
            return

    print("\n✨ All professional enhancements verified successfully!")

if __name__ == "__main__":
    asyncio.run(test_professional_workflow())
